// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akhfabvirnunxztpwqkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFraGZhYnZpcm51bnh6dHB3cWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDM0OTIsImV4cCI6MjA2OTcxOTQ5Mn0.FSsG9w2J2rTNmx1RcLTyLh3zKrclA0xSw4F0Gxk1JQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});